services:
  website:
    container_name: portfolio
    build: ./nuxt-app
    ports:
      - 8080:3000
    env_file:
      - .env
  api:
    container_name: api
    build: ./backend
    ports:
      - 6300:80
    env_file:
      - .env
  postgres:
    container_name: postgres_portfolio
    image: postgres
    volumes:
      - mydb:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  redisdb:
    container_name: redis_portfolio
    image: redis
    env_file:
      - .env
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

volumes:
  mydb:
